#!/bin/bash

echo "🚀 DropShip AI - Complete Live Demo System"
echo "=========================================="
echo ""
echo "✅ Backend Server: Running on http://localhost:8000"
echo "✅ API Docs: http://localhost:8000/docs"
echo "✅ Dashboard: Open dashboard.html in your browser"
echo ""
echo "📋 Quick Tests:"
echo ""
echo "1. Check health:"
echo "   curl http://localhost:8000/api/health"
echo ""
echo "2. Analyze product:"
echo "   curl -X POST http://localhost:8000/api/analyze-product \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"product_name\": \"Wireless Earbuds\"}'"
echo ""
echo "3. Generate content:"
echo "   curl -X POST http://localhost:8000/api/generate-content \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"product_name\": \"Smart Watch\", \"product_type\": \"electronics\"}'"
echo ""
echo "4. Run full demo:"
echo "   python test_live.py"
echo ""
echo "🌐 Open dashboard.html in your web browser to see the visual interface!"
echo ""
